### ISSUE TITLE
Device panics on boot: "No external trustcache found (region len is 0)."

### ISSUE THREAD

**Issue by Cryptiiiic** [tihmstar/ra1nsn0w#12]
iPhone X (10,3 d22ap) on 12.4
I patched img4tool to add bvx2 support to get it to work.
Everything goes as planned except when it boots it panics: `NULL bsd_info pointer.`
`"No external trustcache found (region len is 0)."`
`"No external trustcache found (region len is 0)."`
`"No external trustcache found (region len is 0)."`
`"No external trustcache found (region len is 0)."`

bootargs: `-v rootdev=nd0`
also occurs with just -v

**Comment by krisanovdev** [comment]
Looks like your patched iboot fails to load StaticTrustCache.img4 file to kernel memory. (Signature falidation failed or something). Anyway you can't use this tool for iPhone 7 and higher devices due to Boot progress register (BPR) which is controlled by Secure Enclave. (So can't boot to NAND disk from recovery Mode).

**Comment by Cryptiiiic** [comment]
@MrKris99 If I load it manually from boot commands it works, I just get a kernel panic due to SEP being invalid.

**Comment by tihmstar** [comment]
closing old issue. should be supported by now
