### ISSUE TITLE
Version mismatch for libimg4tool?

### ISSUE THREAD

**Issue by hexploitable** [tihmstar/ra1nsn0w#6]
Hey,

Is this:
https://github.com/tihmstar/ra1nsn0w/blob/master/configure.ac#L37

Meant to be 162, I've compiled the latest img4tool from source and it's 162, wondering if I'm missing something or this is just a simple typo?

**Comment by tihmstar** [comment]
My versioning works as following:
The version number is the amount of commits on the master branch and the "sub version string" is the exact commit hash.

If you git clone img4tool, run `./autogen.sh && make && sudo make install` your version number should match what the commit count says.
There is an _issue_ however if you run `git pull` on an already existing clone.
Because automake does cacheing, simply running `./autogen.sh` again will unfortunatelly not update the version number even if you cloned and compiled the correct code.
I might consider to address this in future, however until then make sure to whenever you update the tools, to either manually remove automake caches, or just delete the whole directory and do a fresh `git clone`. That should make your version number is correct

**Comment by hexploitable** [comment]
Ah no worries, that is exactly what was the case with me :) thx
